### ISSUE TITLE
Fix site search

### ISSUE THREAD

**Issue by lukefretwell** [CivicActions/datascience#23]
This isn't working: https://civicactions.github.io/datascience/search

**Comment by dmundra** [comment]
@lukefretwell this is because the JS is looking for /search.json at the root while the file is actually located https://civicactions.github.io/datascience/search.json (it will be fixed if you get a sub-domain for the site which I presume you might).

**Comment by dmundra** [comment]
@lukefretwell this should be working now with https://datascience.civicactions.com
