### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by lukefretwell** [CivicActions/datascience#25]
**NOTE: The relative links might fix themselves once the subdomain is set up.**

Links on this page are broken: https://civicactions.github.io/datascience/about

* let us know
* calendar
* join us

This page: https://civicactions.github.io/datascience/accessibility

* Open website accessibility issues

This page: https://civicactions.github.io/datascience/posts/hello-world

* We're open.
* Join us
* News

**Comment by lukefretwell** [comment]
@jrozra200 see the config file for accessibility that might resolve some of these:

https://github.com/CivicActions/accessibility/blob/main/_config.yml

Comment out this:

```
# baseurl: /compliance-as-code # the subpath of your site, e.g. /blog
# url: https://govthinktank.github.io/compliance-as-code/ # the base hostname & protocol for your site, e.g. http://example.com
```

**Comment by jrozra200** [comment]
I am going to check this after we get the subdomain mapped.

**Comment by lukefretwell** [comment]
@jrozra200 all of these now work with the exception of the 'Open website accessibility issues' link here:

https://datascience.civicactions.com/accessibility

Just need to change:

`https://github.com/CivicActions/accessibility/labels/accessibility`

to:

`https://github.com/CivicActions/datascience/labels/accessibility`
